//------------------------------------------------------------------------------
// <auto-generated>
//     Bu kod araç tarafından oluşturuldu.
//     Çalışma Zamanı Sürümü:4.0.30319.42000
//
//     Bu dosyada yapılacak değişiklikler yanlış davranışa neden olabilir ve
//     kod yeniden oluşturulursa kaybolur.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Kaynak kodu Microsoft.VSDesigner tarafından otomatik üretilmiş , Sürüm 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace WindowsFormsApplication1.ws_Adana_Lab_Entegre {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="LiosServiceSoap", Namespace="http://tempuri.org/")]
    public partial class LiosService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback AktifTestlerOperationCompleted;
        
        private System.Threading.SendOrPostCallback AktifTestlerParametreliOperationCompleted;
        
        private System.Threading.SendOrPostCallback TestEkleOperationCompleted;
        
        private System.Threading.SendOrPostCallback TestGuncelleOperationCompleted;
        
        private System.Threading.SendOrPostCallback BarkodSonucBilgisiOperationCompleted;
        
        private System.Threading.SendOrPostCallback TCSonucBilgisiOperationCompleted;
        
        private System.Threading.SendOrPostCallback BarkodSilOperationCompleted;
        
        private System.Threading.SendOrPostCallback DuyurulariGetirOperationCompleted;
        
        private System.Threading.SendOrPostCallback BarkodSonucBilgisiPDFOperationCompleted;
        
        private System.Threading.SendOrPostCallback TestKontrolOperationCompleted;
        
        private System.Threading.SendOrPostCallback KonsultasyonKullanicilarOperationCompleted;
        
        private System.Threading.SendOrPostCallback KonsultasyonListesiOperationCompleted;
        
        private System.Threading.SendOrPostCallback KonsultasyonBaslatOperationCompleted;
        
        private System.Threading.SendOrPostCallback KonsultasyonCevapYazOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public LiosService() {
            this.Url = global::WindowsFormsApplication1.Properties.Settings.Default.WindowsFormsApplication1_ws_Adana_Lab_Entegre_EntegreLBYSLabService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event AktifTestlerCompletedEventHandler AktifTestlerCompleted;
        
        /// <remarks/>
        public event AktifTestlerParametreliCompletedEventHandler AktifTestlerParametreliCompleted;
        
        /// <remarks/>
        public event TestEkleCompletedEventHandler TestEkleCompleted;
        
        /// <remarks/>
        public event TestGuncelleCompletedEventHandler TestGuncelleCompleted;
        
        /// <remarks/>
        public event BarkodSonucBilgisiCompletedEventHandler BarkodSonucBilgisiCompleted;
        
        /// <remarks/>
        public event TCSonucBilgisiCompletedEventHandler TCSonucBilgisiCompleted;
        
        /// <remarks/>
        public event BarkodSilCompletedEventHandler BarkodSilCompleted;
        
        /// <remarks/>
        public event DuyurulariGetirCompletedEventHandler DuyurulariGetirCompleted;
        
        /// <remarks/>
        public event BarkodSonucBilgisiPDFCompletedEventHandler BarkodSonucBilgisiPDFCompleted;
        
        /// <remarks/>
        public event TestKontrolCompletedEventHandler TestKontrolCompleted;
        
        /// <remarks/>
        public event KonsultasyonKullanicilarCompletedEventHandler KonsultasyonKullanicilarCompleted;
        
        /// <remarks/>
        public event KonsultasyonListesiCompletedEventHandler KonsultasyonListesiCompleted;
        
        /// <remarks/>
        public event KonsultasyonBaslatCompletedEventHandler KonsultasyonBaslatCompleted;
        
        /// <remarks/>
        public event KonsultasyonCevapYazCompletedEventHandler KonsultasyonCevapYazCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/AktifTestler", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public AktifTest[] AktifTestler(string Kadi, string Ksifre) {
            object[] results = this.Invoke("AktifTestler", new object[] {
                        Kadi,
                        Ksifre});
            return ((AktifTest[])(results[0]));
        }
        
        /// <remarks/>
        public void AktifTestlerAsync(string Kadi, string Ksifre) {
            this.AktifTestlerAsync(Kadi, Ksifre, null);
        }
        
        /// <remarks/>
        public void AktifTestlerAsync(string Kadi, string Ksifre, object userState) {
            if ((this.AktifTestlerOperationCompleted == null)) {
                this.AktifTestlerOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAktifTestlerOperationCompleted);
            }
            this.InvokeAsync("AktifTestler", new object[] {
                        Kadi,
                        Ksifre}, this.AktifTestlerOperationCompleted, userState);
        }
        
        private void OnAktifTestlerOperationCompleted(object arg) {
            if ((this.AktifTestlerCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AktifTestlerCompleted(this, new AktifTestlerCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/AktifTestlerParametreli", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public AktifTestParametre[] AktifTestlerParametreli(string Kadi, string Ksifre) {
            object[] results = this.Invoke("AktifTestlerParametreli", new object[] {
                        Kadi,
                        Ksifre});
            return ((AktifTestParametre[])(results[0]));
        }
        
        /// <remarks/>
        public void AktifTestlerParametreliAsync(string Kadi, string Ksifre) {
            this.AktifTestlerParametreliAsync(Kadi, Ksifre, null);
        }
        
        /// <remarks/>
        public void AktifTestlerParametreliAsync(string Kadi, string Ksifre, object userState) {
            if ((this.AktifTestlerParametreliOperationCompleted == null)) {
                this.AktifTestlerParametreliOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAktifTestlerParametreliOperationCompleted);
            }
            this.InvokeAsync("AktifTestlerParametreli", new object[] {
                        Kadi,
                        Ksifre}, this.AktifTestlerParametreliOperationCompleted, userState);
        }
        
        private void OnAktifTestlerParametreliOperationCompleted(object arg) {
            if ((this.AktifTestlerParametreliCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AktifTestlerParametreliCompleted(this, new AktifTestlerParametreliCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/TestEkle", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public TestEkleSonuc[] TestEkle(
                    string Kadi, 
                    string Ksifre, 
                    string BARKOD, 
                    string TCKIMLIK, 
                    string ADI, 
                    string SOYADI, 
                    string CINSIYET, 
                    System.DateTime DTARIH, 
                    string ONTANI, 
                    string HivGerekce, 
                    string BABAADI, 
                    string NufusKayitliIL, 
                    string IkametIL, 
                    string HastaTelefon, 
                    string TalasemiGerekce, 
                    string HastaBoyBilgisi, 
                    string HastaAgirlikBilgisi, 
                    int[] Test) {
            object[] results = this.Invoke("TestEkle", new object[] {
                        Kadi,
                        Ksifre,
                        BARKOD,
                        TCKIMLIK,
                        ADI,
                        SOYADI,
                        CINSIYET,
                        DTARIH,
                        ONTANI,
                        HivGerekce,
                        BABAADI,
                        NufusKayitliIL,
                        IkametIL,
                        HastaTelefon,
                        TalasemiGerekce,
                        HastaBoyBilgisi,
                        HastaAgirlikBilgisi,
                        Test});
            return ((TestEkleSonuc[])(results[0]));
        }
        
        /// <remarks/>
        public void TestEkleAsync(
                    string Kadi, 
                    string Ksifre, 
                    string BARKOD, 
                    string TCKIMLIK, 
                    string ADI, 
                    string SOYADI, 
                    string CINSIYET, 
                    System.DateTime DTARIH, 
                    string ONTANI, 
                    string HivGerekce, 
                    string BABAADI, 
                    string NufusKayitliIL, 
                    string IkametIL, 
                    string HastaTelefon, 
                    string TalasemiGerekce, 
                    string HastaBoyBilgisi, 
                    string HastaAgirlikBilgisi, 
                    int[] Test) {
            this.TestEkleAsync(Kadi, Ksifre, BARKOD, TCKIMLIK, ADI, SOYADI, CINSIYET, DTARIH, ONTANI, HivGerekce, BABAADI, NufusKayitliIL, IkametIL, HastaTelefon, TalasemiGerekce, HastaBoyBilgisi, HastaAgirlikBilgisi, Test, null);
        }
        
        /// <remarks/>
        public void TestEkleAsync(
                    string Kadi, 
                    string Ksifre, 
                    string BARKOD, 
                    string TCKIMLIK, 
                    string ADI, 
                    string SOYADI, 
                    string CINSIYET, 
                    System.DateTime DTARIH, 
                    string ONTANI, 
                    string HivGerekce, 
                    string BABAADI, 
                    string NufusKayitliIL, 
                    string IkametIL, 
                    string HastaTelefon, 
                    string TalasemiGerekce, 
                    string HastaBoyBilgisi, 
                    string HastaAgirlikBilgisi, 
                    int[] Test, 
                    object userState) {
            if ((this.TestEkleOperationCompleted == null)) {
                this.TestEkleOperationCompleted = new System.Threading.SendOrPostCallback(this.OnTestEkleOperationCompleted);
            }
            this.InvokeAsync("TestEkle", new object[] {
                        Kadi,
                        Ksifre,
                        BARKOD,
                        TCKIMLIK,
                        ADI,
                        SOYADI,
                        CINSIYET,
                        DTARIH,
                        ONTANI,
                        HivGerekce,
                        BABAADI,
                        NufusKayitliIL,
                        IkametIL,
                        HastaTelefon,
                        TalasemiGerekce,
                        HastaBoyBilgisi,
                        HastaAgirlikBilgisi,
                        Test}, this.TestEkleOperationCompleted, userState);
        }
        
        private void OnTestEkleOperationCompleted(object arg) {
            if ((this.TestEkleCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.TestEkleCompleted(this, new TestEkleCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/TestGuncelle", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string TestGuncelle(string BARKOD, string Kadi, string Ksifre, int[] Test) {
            object[] results = this.Invoke("TestGuncelle", new object[] {
                        BARKOD,
                        Kadi,
                        Ksifre,
                        Test});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void TestGuncelleAsync(string BARKOD, string Kadi, string Ksifre, int[] Test) {
            this.TestGuncelleAsync(BARKOD, Kadi, Ksifre, Test, null);
        }
        
        /// <remarks/>
        public void TestGuncelleAsync(string BARKOD, string Kadi, string Ksifre, int[] Test, object userState) {
            if ((this.TestGuncelleOperationCompleted == null)) {
                this.TestGuncelleOperationCompleted = new System.Threading.SendOrPostCallback(this.OnTestGuncelleOperationCompleted);
            }
            this.InvokeAsync("TestGuncelle", new object[] {
                        BARKOD,
                        Kadi,
                        Ksifre,
                        Test}, this.TestGuncelleOperationCompleted, userState);
        }
        
        private void OnTestGuncelleOperationCompleted(object arg) {
            if ((this.TestGuncelleCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.TestGuncelleCompleted(this, new TestGuncelleCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/BarkodSonucBilgisi", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public HastaSonucBilgisi[] BarkodSonucBilgisi(string BARKOD, string Kadi, string Ksifre) {
            object[] results = this.Invoke("BarkodSonucBilgisi", new object[] {
                        BARKOD,
                        Kadi,
                        Ksifre});
            return ((HastaSonucBilgisi[])(results[0]));
        }
        
        /// <remarks/>
        public void BarkodSonucBilgisiAsync(string BARKOD, string Kadi, string Ksifre) {
            this.BarkodSonucBilgisiAsync(BARKOD, Kadi, Ksifre, null);
        }
        
        /// <remarks/>
        public void BarkodSonucBilgisiAsync(string BARKOD, string Kadi, string Ksifre, object userState) {
            if ((this.BarkodSonucBilgisiOperationCompleted == null)) {
                this.BarkodSonucBilgisiOperationCompleted = new System.Threading.SendOrPostCallback(this.OnBarkodSonucBilgisiOperationCompleted);
            }
            this.InvokeAsync("BarkodSonucBilgisi", new object[] {
                        BARKOD,
                        Kadi,
                        Ksifre}, this.BarkodSonucBilgisiOperationCompleted, userState);
        }
        
        private void OnBarkodSonucBilgisiOperationCompleted(object arg) {
            if ((this.BarkodSonucBilgisiCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.BarkodSonucBilgisiCompleted(this, new BarkodSonucBilgisiCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/TCSonucBilgisi", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public HastaSonucToplu[] TCSonucBilgisi(string Kadi, string Ksifre, string TCKIMLIK) {
            object[] results = this.Invoke("TCSonucBilgisi", new object[] {
                        Kadi,
                        Ksifre,
                        TCKIMLIK});
            return ((HastaSonucToplu[])(results[0]));
        }
        
        /// <remarks/>
        public void TCSonucBilgisiAsync(string Kadi, string Ksifre, string TCKIMLIK) {
            this.TCSonucBilgisiAsync(Kadi, Ksifre, TCKIMLIK, null);
        }
        
        /// <remarks/>
        public void TCSonucBilgisiAsync(string Kadi, string Ksifre, string TCKIMLIK, object userState) {
            if ((this.TCSonucBilgisiOperationCompleted == null)) {
                this.TCSonucBilgisiOperationCompleted = new System.Threading.SendOrPostCallback(this.OnTCSonucBilgisiOperationCompleted);
            }
            this.InvokeAsync("TCSonucBilgisi", new object[] {
                        Kadi,
                        Ksifre,
                        TCKIMLIK}, this.TCSonucBilgisiOperationCompleted, userState);
        }
        
        private void OnTCSonucBilgisiOperationCompleted(object arg) {
            if ((this.TCSonucBilgisiCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.TCSonucBilgisiCompleted(this, new TCSonucBilgisiCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/BarkodSil", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string BarkodSil(string Kadi, string Ksifre, string barkod) {
            object[] results = this.Invoke("BarkodSil", new object[] {
                        Kadi,
                        Ksifre,
                        barkod});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void BarkodSilAsync(string Kadi, string Ksifre, string barkod) {
            this.BarkodSilAsync(Kadi, Ksifre, barkod, null);
        }
        
        /// <remarks/>
        public void BarkodSilAsync(string Kadi, string Ksifre, string barkod, object userState) {
            if ((this.BarkodSilOperationCompleted == null)) {
                this.BarkodSilOperationCompleted = new System.Threading.SendOrPostCallback(this.OnBarkodSilOperationCompleted);
            }
            this.InvokeAsync("BarkodSil", new object[] {
                        Kadi,
                        Ksifre,
                        barkod}, this.BarkodSilOperationCompleted, userState);
        }
        
        private void OnBarkodSilOperationCompleted(object arg) {
            if ((this.BarkodSilCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.BarkodSilCompleted(this, new BarkodSilCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/DuyurulariGetir", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public Duyurular[] DuyurulariGetir(string Kadi, string Ksifre) {
            object[] results = this.Invoke("DuyurulariGetir", new object[] {
                        Kadi,
                        Ksifre});
            return ((Duyurular[])(results[0]));
        }
        
        /// <remarks/>
        public void DuyurulariGetirAsync(string Kadi, string Ksifre) {
            this.DuyurulariGetirAsync(Kadi, Ksifre, null);
        }
        
        /// <remarks/>
        public void DuyurulariGetirAsync(string Kadi, string Ksifre, object userState) {
            if ((this.DuyurulariGetirOperationCompleted == null)) {
                this.DuyurulariGetirOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDuyurulariGetirOperationCompleted);
            }
            this.InvokeAsync("DuyurulariGetir", new object[] {
                        Kadi,
                        Ksifre}, this.DuyurulariGetirOperationCompleted, userState);
        }
        
        private void OnDuyurulariGetirOperationCompleted(object arg) {
            if ((this.DuyurulariGetirCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DuyurulariGetirCompleted(this, new DuyurulariGetirCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/BarkodSonucBilgisiPDF", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public HastaSonucPDF[] BarkodSonucBilgisiPDF(string BARKOD, string Kadi, string Ksifre) {
            object[] results = this.Invoke("BarkodSonucBilgisiPDF", new object[] {
                        BARKOD,
                        Kadi,
                        Ksifre});
            return ((HastaSonucPDF[])(results[0]));
        }
        
        /// <remarks/>
        public void BarkodSonucBilgisiPDFAsync(string BARKOD, string Kadi, string Ksifre) {
            this.BarkodSonucBilgisiPDFAsync(BARKOD, Kadi, Ksifre, null);
        }
        
        /// <remarks/>
        public void BarkodSonucBilgisiPDFAsync(string BARKOD, string Kadi, string Ksifre, object userState) {
            if ((this.BarkodSonucBilgisiPDFOperationCompleted == null)) {
                this.BarkodSonucBilgisiPDFOperationCompleted = new System.Threading.SendOrPostCallback(this.OnBarkodSonucBilgisiPDFOperationCompleted);
            }
            this.InvokeAsync("BarkodSonucBilgisiPDF", new object[] {
                        BARKOD,
                        Kadi,
                        Ksifre}, this.BarkodSonucBilgisiPDFOperationCompleted, userState);
        }
        
        private void OnBarkodSonucBilgisiPDFOperationCompleted(object arg) {
            if ((this.BarkodSonucBilgisiPDFCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.BarkodSonucBilgisiPDFCompleted(this, new BarkodSonucBilgisiPDFCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/TestKontrol", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public UyarıSonuc[] TestKontrol(string Kadi, string Ksifre, string BARKOD, string TCKIMLIK, string CINSIYET, string TaniKodu, int[] Test) {
            object[] results = this.Invoke("TestKontrol", new object[] {
                        Kadi,
                        Ksifre,
                        BARKOD,
                        TCKIMLIK,
                        CINSIYET,
                        TaniKodu,
                        Test});
            return ((UyarıSonuc[])(results[0]));
        }
        
        /// <remarks/>
        public void TestKontrolAsync(string Kadi, string Ksifre, string BARKOD, string TCKIMLIK, string CINSIYET, string TaniKodu, int[] Test) {
            this.TestKontrolAsync(Kadi, Ksifre, BARKOD, TCKIMLIK, CINSIYET, TaniKodu, Test, null);
        }
        
        /// <remarks/>
        public void TestKontrolAsync(string Kadi, string Ksifre, string BARKOD, string TCKIMLIK, string CINSIYET, string TaniKodu, int[] Test, object userState) {
            if ((this.TestKontrolOperationCompleted == null)) {
                this.TestKontrolOperationCompleted = new System.Threading.SendOrPostCallback(this.OnTestKontrolOperationCompleted);
            }
            this.InvokeAsync("TestKontrol", new object[] {
                        Kadi,
                        Ksifre,
                        BARKOD,
                        TCKIMLIK,
                        CINSIYET,
                        TaniKodu,
                        Test}, this.TestKontrolOperationCompleted, userState);
        }
        
        private void OnTestKontrolOperationCompleted(object arg) {
            if ((this.TestKontrolCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.TestKontrolCompleted(this, new TestKontrolCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/KonsultasyonKullanicilar", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public KonsultasyonKullaniciListe[] KonsultasyonKullanicilar(string Kadi, string Ksifre) {
            object[] results = this.Invoke("KonsultasyonKullanicilar", new object[] {
                        Kadi,
                        Ksifre});
            return ((KonsultasyonKullaniciListe[])(results[0]));
        }
        
        /// <remarks/>
        public void KonsultasyonKullanicilarAsync(string Kadi, string Ksifre) {
            this.KonsultasyonKullanicilarAsync(Kadi, Ksifre, null);
        }
        
        /// <remarks/>
        public void KonsultasyonKullanicilarAsync(string Kadi, string Ksifre, object userState) {
            if ((this.KonsultasyonKullanicilarOperationCompleted == null)) {
                this.KonsultasyonKullanicilarOperationCompleted = new System.Threading.SendOrPostCallback(this.OnKonsultasyonKullanicilarOperationCompleted);
            }
            this.InvokeAsync("KonsultasyonKullanicilar", new object[] {
                        Kadi,
                        Ksifre}, this.KonsultasyonKullanicilarOperationCompleted, userState);
        }
        
        private void OnKonsultasyonKullanicilarOperationCompleted(object arg) {
            if ((this.KonsultasyonKullanicilarCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.KonsultasyonKullanicilarCompleted(this, new KonsultasyonKullanicilarCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/KonsultasyonListesi", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public Konsultasyon[] KonsultasyonListesi(string Kadi, string Ksifre, string KonsultasyonNo, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] System.Nullable<bool> SadeceYenileriGetir) {
            object[] results = this.Invoke("KonsultasyonListesi", new object[] {
                        Kadi,
                        Ksifre,
                        KonsultasyonNo,
                        SadeceYenileriGetir});
            return ((Konsultasyon[])(results[0]));
        }
        
        /// <remarks/>
        public void KonsultasyonListesiAsync(string Kadi, string Ksifre, string KonsultasyonNo, System.Nullable<bool> SadeceYenileriGetir) {
            this.KonsultasyonListesiAsync(Kadi, Ksifre, KonsultasyonNo, SadeceYenileriGetir, null);
        }
        
        /// <remarks/>
        public void KonsultasyonListesiAsync(string Kadi, string Ksifre, string KonsultasyonNo, System.Nullable<bool> SadeceYenileriGetir, object userState) {
            if ((this.KonsultasyonListesiOperationCompleted == null)) {
                this.KonsultasyonListesiOperationCompleted = new System.Threading.SendOrPostCallback(this.OnKonsultasyonListesiOperationCompleted);
            }
            this.InvokeAsync("KonsultasyonListesi", new object[] {
                        Kadi,
                        Ksifre,
                        KonsultasyonNo,
                        SadeceYenileriGetir}, this.KonsultasyonListesiOperationCompleted, userState);
        }
        
        private void OnKonsultasyonListesiOperationCompleted(object arg) {
            if ((this.KonsultasyonListesiCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.KonsultasyonListesiCompleted(this, new KonsultasyonListesiCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/KonsultasyonBaslat", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public KonsultasyonBaslatSonuc[] KonsultasyonBaslat(string Kadi, string Ksifre, string IstenilenKullaniciNo, string Konu, string Icerik) {
            object[] results = this.Invoke("KonsultasyonBaslat", new object[] {
                        Kadi,
                        Ksifre,
                        IstenilenKullaniciNo,
                        Konu,
                        Icerik});
            return ((KonsultasyonBaslatSonuc[])(results[0]));
        }
        
        /// <remarks/>
        public void KonsultasyonBaslatAsync(string Kadi, string Ksifre, string IstenilenKullaniciNo, string Konu, string Icerik) {
            this.KonsultasyonBaslatAsync(Kadi, Ksifre, IstenilenKullaniciNo, Konu, Icerik, null);
        }
        
        /// <remarks/>
        public void KonsultasyonBaslatAsync(string Kadi, string Ksifre, string IstenilenKullaniciNo, string Konu, string Icerik, object userState) {
            if ((this.KonsultasyonBaslatOperationCompleted == null)) {
                this.KonsultasyonBaslatOperationCompleted = new System.Threading.SendOrPostCallback(this.OnKonsultasyonBaslatOperationCompleted);
            }
            this.InvokeAsync("KonsultasyonBaslat", new object[] {
                        Kadi,
                        Ksifre,
                        IstenilenKullaniciNo,
                        Konu,
                        Icerik}, this.KonsultasyonBaslatOperationCompleted, userState);
        }
        
        private void OnKonsultasyonBaslatOperationCompleted(object arg) {
            if ((this.KonsultasyonBaslatCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.KonsultasyonBaslatCompleted(this, new KonsultasyonBaslatCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/KonsultasyonCevapYaz", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public KonsultasyonCevapYazSonuc[] KonsultasyonCevapYaz(string Kadi, string Ksifre, string KonsultasyonNo, string Cevap) {
            object[] results = this.Invoke("KonsultasyonCevapYaz", new object[] {
                        Kadi,
                        Ksifre,
                        KonsultasyonNo,
                        Cevap});
            return ((KonsultasyonCevapYazSonuc[])(results[0]));
        }
        
        /// <remarks/>
        public void KonsultasyonCevapYazAsync(string Kadi, string Ksifre, string KonsultasyonNo, string Cevap) {
            this.KonsultasyonCevapYazAsync(Kadi, Ksifre, KonsultasyonNo, Cevap, null);
        }
        
        /// <remarks/>
        public void KonsultasyonCevapYazAsync(string Kadi, string Ksifre, string KonsultasyonNo, string Cevap, object userState) {
            if ((this.KonsultasyonCevapYazOperationCompleted == null)) {
                this.KonsultasyonCevapYazOperationCompleted = new System.Threading.SendOrPostCallback(this.OnKonsultasyonCevapYazOperationCompleted);
            }
            this.InvokeAsync("KonsultasyonCevapYaz", new object[] {
                        Kadi,
                        Ksifre,
                        KonsultasyonNo,
                        Cevap}, this.KonsultasyonCevapYazOperationCompleted, userState);
        }
        
        private void OnKonsultasyonCevapYazOperationCompleted(object arg) {
            if ((this.KonsultasyonCevapYazCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.KonsultasyonCevapYazCompleted(this, new KonsultasyonCevapYazCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class AktifTest {
        
        private string testGrupAdiField;
        
        private string butceKoduField;
        
        private string testAdiField;
        
        private string kisaAdField;
        
        private string testIDField;
        
        private string testOrnekTipiField;
        
        private string hataField;
        
        /// <remarks/>
        public string TestGrupAdi {
            get {
                return this.testGrupAdiField;
            }
            set {
                this.testGrupAdiField = value;
            }
        }
        
        /// <remarks/>
        public string ButceKodu {
            get {
                return this.butceKoduField;
            }
            set {
                this.butceKoduField = value;
            }
        }
        
        /// <remarks/>
        public string TestAdi {
            get {
                return this.testAdiField;
            }
            set {
                this.testAdiField = value;
            }
        }
        
        /// <remarks/>
        public string KisaAd {
            get {
                return this.kisaAdField;
            }
            set {
                this.kisaAdField = value;
            }
        }
        
        /// <remarks/>
        public string TestID {
            get {
                return this.testIDField;
            }
            set {
                this.testIDField = value;
            }
        }
        
        /// <remarks/>
        public string TestOrnekTipi {
            get {
                return this.testOrnekTipiField;
            }
            set {
                this.testOrnekTipiField = value;
            }
        }
        
        /// <remarks/>
        public string Hata {
            get {
                return this.hataField;
            }
            set {
                this.hataField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class KonsultasyonCevapYazSonuc {
        
        private string konsultasyonNoField;
        
        private string islemSonucuField;
        
        private string hataField;
        
        /// <remarks/>
        public string KonsultasyonNo {
            get {
                return this.konsultasyonNoField;
            }
            set {
                this.konsultasyonNoField = value;
            }
        }
        
        /// <remarks/>
        public string IslemSonucu {
            get {
                return this.islemSonucuField;
            }
            set {
                this.islemSonucuField = value;
            }
        }
        
        /// <remarks/>
        public string Hata {
            get {
                return this.hataField;
            }
            set {
                this.hataField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class KonsultasyonBaslatSonuc {
        
        private string konsultasyonNoField;
        
        private string islemSonucuField;
        
        private string hataField;
        
        /// <remarks/>
        public string KonsultasyonNo {
            get {
                return this.konsultasyonNoField;
            }
            set {
                this.konsultasyonNoField = value;
            }
        }
        
        /// <remarks/>
        public string IslemSonucu {
            get {
                return this.islemSonucuField;
            }
            set {
                this.islemSonucuField = value;
            }
        }
        
        /// <remarks/>
        public string Hata {
            get {
                return this.hataField;
            }
            set {
                this.hataField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Konsultasyon {
        
        private string konsultasyonNoField;
        
        private string isteyenKullaniciField;
        
        private string istenilenKullaniciField;
        
        private string istenmeTarihiField;
        
        private string konuField;
        
        private string icerikField;
        
        private string okunmaDurumuField;
        
        private string okuyanKullaniciField;
        
        private string okunmaTarihiField;
        
        private string cevapDurumuField;
        
        private string cevaplayanKullaniciField;
        
        private string cevapTarihiField;
        
        private string cevapOkunmaDurumuField;
        
        private string cevapOkunmaTarihiField;
        
        private string hataField;
        
        /// <remarks/>
        public string KonsultasyonNo {
            get {
                return this.konsultasyonNoField;
            }
            set {
                this.konsultasyonNoField = value;
            }
        }
        
        /// <remarks/>
        public string IsteyenKullanici {
            get {
                return this.isteyenKullaniciField;
            }
            set {
                this.isteyenKullaniciField = value;
            }
        }
        
        /// <remarks/>
        public string IstenilenKullanici {
            get {
                return this.istenilenKullaniciField;
            }
            set {
                this.istenilenKullaniciField = value;
            }
        }
        
        /// <remarks/>
        public string IstenmeTarihi {
            get {
                return this.istenmeTarihiField;
            }
            set {
                this.istenmeTarihiField = value;
            }
        }
        
        /// <remarks/>
        public string Konu {
            get {
                return this.konuField;
            }
            set {
                this.konuField = value;
            }
        }
        
        /// <remarks/>
        public string Icerik {
            get {
                return this.icerikField;
            }
            set {
                this.icerikField = value;
            }
        }
        
        /// <remarks/>
        public string OkunmaDurumu {
            get {
                return this.okunmaDurumuField;
            }
            set {
                this.okunmaDurumuField = value;
            }
        }
        
        /// <remarks/>
        public string OkuyanKullanici {
            get {
                return this.okuyanKullaniciField;
            }
            set {
                this.okuyanKullaniciField = value;
            }
        }
        
        /// <remarks/>
        public string OkunmaTarihi {
            get {
                return this.okunmaTarihiField;
            }
            set {
                this.okunmaTarihiField = value;
            }
        }
        
        /// <remarks/>
        public string CevapDurumu {
            get {
                return this.cevapDurumuField;
            }
            set {
                this.cevapDurumuField = value;
            }
        }
        
        /// <remarks/>
        public string CevaplayanKullanici {
            get {
                return this.cevaplayanKullaniciField;
            }
            set {
                this.cevaplayanKullaniciField = value;
            }
        }
        
        /// <remarks/>
        public string CevapTarihi {
            get {
                return this.cevapTarihiField;
            }
            set {
                this.cevapTarihiField = value;
            }
        }
        
        /// <remarks/>
        public string CevapOkunmaDurumu {
            get {
                return this.cevapOkunmaDurumuField;
            }
            set {
                this.cevapOkunmaDurumuField = value;
            }
        }
        
        /// <remarks/>
        public string CevapOkunmaTarihi {
            get {
                return this.cevapOkunmaTarihiField;
            }
            set {
                this.cevapOkunmaTarihiField = value;
            }
        }
        
        /// <remarks/>
        public string Hata {
            get {
                return this.hataField;
            }
            set {
                this.hataField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class KonsultasyonKullaniciListe {
        
        private string kullaniciNoField;
        
        private string kullaniciAdiSoyadiField;
        
        private string hataField;
        
        /// <remarks/>
        public string KullaniciNo {
            get {
                return this.kullaniciNoField;
            }
            set {
                this.kullaniciNoField = value;
            }
        }
        
        /// <remarks/>
        public string KullaniciAdiSoyadi {
            get {
                return this.kullaniciAdiSoyadiField;
            }
            set {
                this.kullaniciAdiSoyadiField = value;
            }
        }
        
        /// <remarks/>
        public string Hata {
            get {
                return this.hataField;
            }
            set {
                this.hataField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class UyarıSonuc {
        
        private string testIDField;
        
        private string testUyariDurumuField;
        
        private string testUyariAciklamasiField;
        
        private string hataField;
        
        /// <remarks/>
        public string testID {
            get {
                return this.testIDField;
            }
            set {
                this.testIDField = value;
            }
        }
        
        /// <remarks/>
        public string testUyariDurumu {
            get {
                return this.testUyariDurumuField;
            }
            set {
                this.testUyariDurumuField = value;
            }
        }
        
        /// <remarks/>
        public string testUyariAciklamasi {
            get {
                return this.testUyariAciklamasiField;
            }
            set {
                this.testUyariAciklamasiField = value;
            }
        }
        
        /// <remarks/>
        public string Hata {
            get {
                return this.hataField;
            }
            set {
                this.hataField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class HastaSonucPDF {
        
        private string sonucPDFField;
        
        private string ekSonucPDFField;
        
        private string hataField;
        
        /// <remarks/>
        public string SonucPDF {
            get {
                return this.sonucPDFField;
            }
            set {
                this.sonucPDFField = value;
            }
        }
        
        /// <remarks/>
        public string EkSonucPDF {
            get {
                return this.ekSonucPDFField;
            }
            set {
                this.ekSonucPDFField = value;
            }
        }
        
        /// <remarks/>
        public string Hata {
            get {
                return this.hataField;
            }
            set {
                this.hataField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Duyurular {
        
        private string duyuruIDField;
        
        private string baslikField;
        
        private string icerikField;
        
        private string tarihField;
        
        private string hataField;
        
        /// <remarks/>
        public string DuyuruID {
            get {
                return this.duyuruIDField;
            }
            set {
                this.duyuruIDField = value;
            }
        }
        
        /// <remarks/>
        public string Baslik {
            get {
                return this.baslikField;
            }
            set {
                this.baslikField = value;
            }
        }
        
        /// <remarks/>
        public string Icerik {
            get {
                return this.icerikField;
            }
            set {
                this.icerikField = value;
            }
        }
        
        /// <remarks/>
        public string Tarih {
            get {
                return this.tarihField;
            }
            set {
                this.tarihField = value;
            }
        }
        
        /// <remarks/>
        public string Hata {
            get {
                return this.hataField;
            }
            set {
                this.hataField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class HastaSonucToplu {
        
        private HastaSonucBilgisi[] testSonuclariGenelField;
        
        private string hataField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public HastaSonucBilgisi[] TestSonuclariGenel {
            get {
                return this.testSonuclariGenelField;
            }
            set {
                this.testSonuclariGenelField = value;
            }
        }
        
        /// <remarks/>
        public string Hata {
            get {
                return this.hataField;
            }
            set {
                this.hataField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class HastaSonucBilgisi {
        
        private string barkodField;
        
        private string tCKimlikNoField;
        
        private string adiSoyadiField;
        
        private string babaAdiField;
        
        private string dogumTarihiField;
        
        private string cinsiyetField;
        
        private string klinikAdiField;
        
        private string birimAdiField;
        
        private string kayitTarihiField;
        
        private string istemTarihiField;
        
        private string aciklamaField;
        
        private string aileHekimiAdiField;
        
        private string yasField;
        
        private string ornekAlmaTarihiField;
        
        private string aileHekimIDField;
        
        private string hataField;
        
        private SonucBilgi[] testSonuclariField;
        
        /// <remarks/>
        public string Barkod {
            get {
                return this.barkodField;
            }
            set {
                this.barkodField = value;
            }
        }
        
        /// <remarks/>
        public string TCKimlikNo {
            get {
                return this.tCKimlikNoField;
            }
            set {
                this.tCKimlikNoField = value;
            }
        }
        
        /// <remarks/>
        public string AdiSoyadi {
            get {
                return this.adiSoyadiField;
            }
            set {
                this.adiSoyadiField = value;
            }
        }
        
        /// <remarks/>
        public string BabaAdi {
            get {
                return this.babaAdiField;
            }
            set {
                this.babaAdiField = value;
            }
        }
        
        /// <remarks/>
        public string DogumTarihi {
            get {
                return this.dogumTarihiField;
            }
            set {
                this.dogumTarihiField = value;
            }
        }
        
        /// <remarks/>
        public string Cinsiyet {
            get {
                return this.cinsiyetField;
            }
            set {
                this.cinsiyetField = value;
            }
        }
        
        /// <remarks/>
        public string KlinikAdi {
            get {
                return this.klinikAdiField;
            }
            set {
                this.klinikAdiField = value;
            }
        }
        
        /// <remarks/>
        public string BirimAdi {
            get {
                return this.birimAdiField;
            }
            set {
                this.birimAdiField = value;
            }
        }
        
        /// <remarks/>
        public string KayitTarihi {
            get {
                return this.kayitTarihiField;
            }
            set {
                this.kayitTarihiField = value;
            }
        }
        
        /// <remarks/>
        public string istemTarihi {
            get {
                return this.istemTarihiField;
            }
            set {
                this.istemTarihiField = value;
            }
        }
        
        /// <remarks/>
        public string Aciklama {
            get {
                return this.aciklamaField;
            }
            set {
                this.aciklamaField = value;
            }
        }
        
        /// <remarks/>
        public string AileHekimiAdi {
            get {
                return this.aileHekimiAdiField;
            }
            set {
                this.aileHekimiAdiField = value;
            }
        }
        
        /// <remarks/>
        public string Yas {
            get {
                return this.yasField;
            }
            set {
                this.yasField = value;
            }
        }
        
        /// <remarks/>
        public string OrnekAlmaTarihi {
            get {
                return this.ornekAlmaTarihiField;
            }
            set {
                this.ornekAlmaTarihiField = value;
            }
        }
        
        /// <remarks/>
        public string AileHekimID {
            get {
                return this.aileHekimIDField;
            }
            set {
                this.aileHekimIDField = value;
            }
        }
        
        /// <remarks/>
        public string Hata {
            get {
                return this.hataField;
            }
            set {
                this.hataField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public SonucBilgi[] TestSonuclari {
            get {
                return this.testSonuclariField;
            }
            set {
                this.testSonuclariField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class SonucBilgi {
        
        private string testGrupAdiField;
        
        private string testAdiField;
        
        private string testParametreAdiField;
        
        private string testIDField;
        
        private string ornekTipiField;
        
        private string sonucField;
        
        private string sonucBirimField;
        
        private string sonucReferansField;
        
        private string sonucDurumField;
        
        private string sonucOnayTarihiField;
        
        private string sonucYorumField;
        
        private string sonucAciklamaField;
        
        private string loincKoduField;
        
        private string sutKoduField;
        
        /// <remarks/>
        public string TestGrupAdi {
            get {
                return this.testGrupAdiField;
            }
            set {
                this.testGrupAdiField = value;
            }
        }
        
        /// <remarks/>
        public string TestAdi {
            get {
                return this.testAdiField;
            }
            set {
                this.testAdiField = value;
            }
        }
        
        /// <remarks/>
        public string TestParametreAdi {
            get {
                return this.testParametreAdiField;
            }
            set {
                this.testParametreAdiField = value;
            }
        }
        
        /// <remarks/>
        public string TestID {
            get {
                return this.testIDField;
            }
            set {
                this.testIDField = value;
            }
        }
        
        /// <remarks/>
        public string OrnekTipi {
            get {
                return this.ornekTipiField;
            }
            set {
                this.ornekTipiField = value;
            }
        }
        
        /// <remarks/>
        public string Sonuc {
            get {
                return this.sonucField;
            }
            set {
                this.sonucField = value;
            }
        }
        
        /// <remarks/>
        public string SonucBirim {
            get {
                return this.sonucBirimField;
            }
            set {
                this.sonucBirimField = value;
            }
        }
        
        /// <remarks/>
        public string SonucReferans {
            get {
                return this.sonucReferansField;
            }
            set {
                this.sonucReferansField = value;
            }
        }
        
        /// <remarks/>
        public string SonucDurum {
            get {
                return this.sonucDurumField;
            }
            set {
                this.sonucDurumField = value;
            }
        }
        
        /// <remarks/>
        public string SonucOnayTarihi {
            get {
                return this.sonucOnayTarihiField;
            }
            set {
                this.sonucOnayTarihiField = value;
            }
        }
        
        /// <remarks/>
        public string SonucYorum {
            get {
                return this.sonucYorumField;
            }
            set {
                this.sonucYorumField = value;
            }
        }
        
        /// <remarks/>
        public string SonucAciklama {
            get {
                return this.sonucAciklamaField;
            }
            set {
                this.sonucAciklamaField = value;
            }
        }
        
        /// <remarks/>
        public string LoincKodu {
            get {
                return this.loincKoduField;
            }
            set {
                this.loincKoduField = value;
            }
        }
        
        /// <remarks/>
        public string SutKodu {
            get {
                return this.sutKoduField;
            }
            set {
                this.sutKoduField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class TestEkleSonuc {
        
        private string sonucField;
        
        private string barkodField;
        
        /// <remarks/>
        public string Sonuc {
            get {
                return this.sonucField;
            }
            set {
                this.sonucField = value;
            }
        }
        
        /// <remarks/>
        public string Barkod {
            get {
                return this.barkodField;
            }
            set {
                this.barkodField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class AktifTestParametre {
        
        private string testIDField;
        
        private string parametreAdiField;
        
        private string parametreLabKoduField;
        
        private string testAdiField;
        
        private string hataField;
        
        /// <remarks/>
        public string TestID {
            get {
                return this.testIDField;
            }
            set {
                this.testIDField = value;
            }
        }
        
        /// <remarks/>
        public string ParametreAdi {
            get {
                return this.parametreAdiField;
            }
            set {
                this.parametreAdiField = value;
            }
        }
        
        /// <remarks/>
        public string ParametreLabKodu {
            get {
                return this.parametreLabKoduField;
            }
            set {
                this.parametreLabKoduField = value;
            }
        }
        
        /// <remarks/>
        public string TestAdi {
            get {
                return this.testAdiField;
            }
            set {
                this.testAdiField = value;
            }
        }
        
        /// <remarks/>
        public string Hata {
            get {
                return this.hataField;
            }
            set {
                this.hataField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void AktifTestlerCompletedEventHandler(object sender, AktifTestlerCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AktifTestlerCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal AktifTestlerCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public AktifTest[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((AktifTest[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void AktifTestlerParametreliCompletedEventHandler(object sender, AktifTestlerParametreliCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AktifTestlerParametreliCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal AktifTestlerParametreliCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public AktifTestParametre[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((AktifTestParametre[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void TestEkleCompletedEventHandler(object sender, TestEkleCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class TestEkleCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal TestEkleCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public TestEkleSonuc[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((TestEkleSonuc[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void TestGuncelleCompletedEventHandler(object sender, TestGuncelleCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class TestGuncelleCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal TestGuncelleCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void BarkodSonucBilgisiCompletedEventHandler(object sender, BarkodSonucBilgisiCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class BarkodSonucBilgisiCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal BarkodSonucBilgisiCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public HastaSonucBilgisi[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((HastaSonucBilgisi[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void TCSonucBilgisiCompletedEventHandler(object sender, TCSonucBilgisiCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class TCSonucBilgisiCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal TCSonucBilgisiCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public HastaSonucToplu[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((HastaSonucToplu[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void BarkodSilCompletedEventHandler(object sender, BarkodSilCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class BarkodSilCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal BarkodSilCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void DuyurulariGetirCompletedEventHandler(object sender, DuyurulariGetirCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class DuyurulariGetirCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal DuyurulariGetirCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Duyurular[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Duyurular[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void BarkodSonucBilgisiPDFCompletedEventHandler(object sender, BarkodSonucBilgisiPDFCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class BarkodSonucBilgisiPDFCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal BarkodSonucBilgisiPDFCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public HastaSonucPDF[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((HastaSonucPDF[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void TestKontrolCompletedEventHandler(object sender, TestKontrolCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class TestKontrolCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal TestKontrolCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public UyarıSonuc[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((UyarıSonuc[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void KonsultasyonKullanicilarCompletedEventHandler(object sender, KonsultasyonKullanicilarCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class KonsultasyonKullanicilarCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal KonsultasyonKullanicilarCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public KonsultasyonKullaniciListe[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((KonsultasyonKullaniciListe[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void KonsultasyonListesiCompletedEventHandler(object sender, KonsultasyonListesiCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class KonsultasyonListesiCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal KonsultasyonListesiCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Konsultasyon[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Konsultasyon[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void KonsultasyonBaslatCompletedEventHandler(object sender, KonsultasyonBaslatCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class KonsultasyonBaslatCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal KonsultasyonBaslatCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public KonsultasyonBaslatSonuc[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((KonsultasyonBaslatSonuc[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void KonsultasyonCevapYazCompletedEventHandler(object sender, KonsultasyonCevapYazCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class KonsultasyonCevapYazCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal KonsultasyonCevapYazCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public KonsultasyonCevapYazSonuc[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((KonsultasyonCevapYazSonuc[])(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591