//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApplication1.ws_Adana_Lab_Entegre {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AktifTest", Namespace="http://www.esy.com.tr/")]
    [System.SerializableAttribute()]
    public partial class AktifTest : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TestGrupAdiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ButceKoduField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TestAdiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string KisaAdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TestIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TestOrnekTipiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string HataField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string TestGrupAdi {
            get {
                return this.TestGrupAdiField;
            }
            set {
                if ((object.ReferenceEquals(this.TestGrupAdiField, value) != true)) {
                    this.TestGrupAdiField = value;
                    this.RaisePropertyChanged("TestGrupAdi");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string ButceKodu {
            get {
                return this.ButceKoduField;
            }
            set {
                if ((object.ReferenceEquals(this.ButceKoduField, value) != true)) {
                    this.ButceKoduField = value;
                    this.RaisePropertyChanged("ButceKodu");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string TestAdi {
            get {
                return this.TestAdiField;
            }
            set {
                if ((object.ReferenceEquals(this.TestAdiField, value) != true)) {
                    this.TestAdiField = value;
                    this.RaisePropertyChanged("TestAdi");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string KisaAd {
            get {
                return this.KisaAdField;
            }
            set {
                if ((object.ReferenceEquals(this.KisaAdField, value) != true)) {
                    this.KisaAdField = value;
                    this.RaisePropertyChanged("KisaAd");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string TestID {
            get {
                return this.TestIDField;
            }
            set {
                if ((object.ReferenceEquals(this.TestIDField, value) != true)) {
                    this.TestIDField = value;
                    this.RaisePropertyChanged("TestID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string TestOrnekTipi {
            get {
                return this.TestOrnekTipiField;
            }
            set {
                if ((object.ReferenceEquals(this.TestOrnekTipiField, value) != true)) {
                    this.TestOrnekTipiField = value;
                    this.RaisePropertyChanged("TestOrnekTipi");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string Hata {
            get {
                return this.HataField;
            }
            set {
                if ((object.ReferenceEquals(this.HataField, value) != true)) {
                    this.HataField = value;
                    this.RaisePropertyChanged("Hata");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfInt", Namespace="http://www.esy.com.tr/", ItemName="int")]
    [System.SerializableAttribute()]
    public class ArrayOfInt : System.Collections.Generic.List<int> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TestEkleSonuc", Namespace="http://www.esy.com.tr/")]
    [System.SerializableAttribute()]
    public partial class TestEkleSonuc : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SonucField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BarkodField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Sonuc {
            get {
                return this.SonucField;
            }
            set {
                if ((object.ReferenceEquals(this.SonucField, value) != true)) {
                    this.SonucField = value;
                    this.RaisePropertyChanged("Sonuc");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Barkod {
            get {
                return this.BarkodField;
            }
            set {
                if ((object.ReferenceEquals(this.BarkodField, value) != true)) {
                    this.BarkodField = value;
                    this.RaisePropertyChanged("Barkod");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="HastaSonucBilgisi", Namespace="http://www.esy.com.tr/")]
    [System.SerializableAttribute()]
    public partial class HastaSonucBilgisi : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BarkodField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TCKimlikNoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AdiSoyadiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BabaAdiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DogumTarihiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CinsiyetField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string KlinikAdiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BirimAdiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string KayitTarihiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string istemTarihiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AciklamaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AileHekimiAdiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string YasField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OrnekAlmaTarihiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string HataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WindowsFormsApplication1.ws_Adana_Lab_Entegre.SonucBilgi[] TestSonuclariField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Barkod {
            get {
                return this.BarkodField;
            }
            set {
                if ((object.ReferenceEquals(this.BarkodField, value) != true)) {
                    this.BarkodField = value;
                    this.RaisePropertyChanged("Barkod");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string TCKimlikNo {
            get {
                return this.TCKimlikNoField;
            }
            set {
                if ((object.ReferenceEquals(this.TCKimlikNoField, value) != true)) {
                    this.TCKimlikNoField = value;
                    this.RaisePropertyChanged("TCKimlikNo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string AdiSoyadi {
            get {
                return this.AdiSoyadiField;
            }
            set {
                if ((object.ReferenceEquals(this.AdiSoyadiField, value) != true)) {
                    this.AdiSoyadiField = value;
                    this.RaisePropertyChanged("AdiSoyadi");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string BabaAdi {
            get {
                return this.BabaAdiField;
            }
            set {
                if ((object.ReferenceEquals(this.BabaAdiField, value) != true)) {
                    this.BabaAdiField = value;
                    this.RaisePropertyChanged("BabaAdi");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string DogumTarihi {
            get {
                return this.DogumTarihiField;
            }
            set {
                if ((object.ReferenceEquals(this.DogumTarihiField, value) != true)) {
                    this.DogumTarihiField = value;
                    this.RaisePropertyChanged("DogumTarihi");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string Cinsiyet {
            get {
                return this.CinsiyetField;
            }
            set {
                if ((object.ReferenceEquals(this.CinsiyetField, value) != true)) {
                    this.CinsiyetField = value;
                    this.RaisePropertyChanged("Cinsiyet");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string KlinikAdi {
            get {
                return this.KlinikAdiField;
            }
            set {
                if ((object.ReferenceEquals(this.KlinikAdiField, value) != true)) {
                    this.KlinikAdiField = value;
                    this.RaisePropertyChanged("KlinikAdi");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string BirimAdi {
            get {
                return this.BirimAdiField;
            }
            set {
                if ((object.ReferenceEquals(this.BirimAdiField, value) != true)) {
                    this.BirimAdiField = value;
                    this.RaisePropertyChanged("BirimAdi");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string KayitTarihi {
            get {
                return this.KayitTarihiField;
            }
            set {
                if ((object.ReferenceEquals(this.KayitTarihiField, value) != true)) {
                    this.KayitTarihiField = value;
                    this.RaisePropertyChanged("KayitTarihi");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
        public string istemTarihi {
            get {
                return this.istemTarihiField;
            }
            set {
                if ((object.ReferenceEquals(this.istemTarihiField, value) != true)) {
                    this.istemTarihiField = value;
                    this.RaisePropertyChanged("istemTarihi");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=10)]
        public string Aciklama {
            get {
                return this.AciklamaField;
            }
            set {
                if ((object.ReferenceEquals(this.AciklamaField, value) != true)) {
                    this.AciklamaField = value;
                    this.RaisePropertyChanged("Aciklama");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=11)]
        public string AileHekimiAdi {
            get {
                return this.AileHekimiAdiField;
            }
            set {
                if ((object.ReferenceEquals(this.AileHekimiAdiField, value) != true)) {
                    this.AileHekimiAdiField = value;
                    this.RaisePropertyChanged("AileHekimiAdi");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=12)]
        public string Yas {
            get {
                return this.YasField;
            }
            set {
                if ((object.ReferenceEquals(this.YasField, value) != true)) {
                    this.YasField = value;
                    this.RaisePropertyChanged("Yas");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=13)]
        public string OrnekAlmaTarihi {
            get {
                return this.OrnekAlmaTarihiField;
            }
            set {
                if ((object.ReferenceEquals(this.OrnekAlmaTarihiField, value) != true)) {
                    this.OrnekAlmaTarihiField = value;
                    this.RaisePropertyChanged("OrnekAlmaTarihi");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=14)]
        public string Hata {
            get {
                return this.HataField;
            }
            set {
                if ((object.ReferenceEquals(this.HataField, value) != true)) {
                    this.HataField = value;
                    this.RaisePropertyChanged("Hata");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=15)]
        public WindowsFormsApplication1.ws_Adana_Lab_Entegre.SonucBilgi[] TestSonuclari {
            get {
                return this.TestSonuclariField;
            }
            set {
                if ((object.ReferenceEquals(this.TestSonuclariField, value) != true)) {
                    this.TestSonuclariField = value;
                    this.RaisePropertyChanged("TestSonuclari");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SonucBilgi", Namespace="http://www.esy.com.tr/")]
    [System.SerializableAttribute()]
    public partial class SonucBilgi : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TestGrupAdiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TestAdiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TestParametreAdiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TestIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OrnekTipiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SonucField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SonucBirimField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SonucReferansField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SonucDurumField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SonucOnayTarihiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SonucYorumField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SonucAciklamaField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string TestGrupAdi {
            get {
                return this.TestGrupAdiField;
            }
            set {
                if ((object.ReferenceEquals(this.TestGrupAdiField, value) != true)) {
                    this.TestGrupAdiField = value;
                    this.RaisePropertyChanged("TestGrupAdi");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string TestAdi {
            get {
                return this.TestAdiField;
            }
            set {
                if ((object.ReferenceEquals(this.TestAdiField, value) != true)) {
                    this.TestAdiField = value;
                    this.RaisePropertyChanged("TestAdi");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string TestParametreAdi {
            get {
                return this.TestParametreAdiField;
            }
            set {
                if ((object.ReferenceEquals(this.TestParametreAdiField, value) != true)) {
                    this.TestParametreAdiField = value;
                    this.RaisePropertyChanged("TestParametreAdi");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string TestID {
            get {
                return this.TestIDField;
            }
            set {
                if ((object.ReferenceEquals(this.TestIDField, value) != true)) {
                    this.TestIDField = value;
                    this.RaisePropertyChanged("TestID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string OrnekTipi {
            get {
                return this.OrnekTipiField;
            }
            set {
                if ((object.ReferenceEquals(this.OrnekTipiField, value) != true)) {
                    this.OrnekTipiField = value;
                    this.RaisePropertyChanged("OrnekTipi");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string Sonuc {
            get {
                return this.SonucField;
            }
            set {
                if ((object.ReferenceEquals(this.SonucField, value) != true)) {
                    this.SonucField = value;
                    this.RaisePropertyChanged("Sonuc");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string SonucBirim {
            get {
                return this.SonucBirimField;
            }
            set {
                if ((object.ReferenceEquals(this.SonucBirimField, value) != true)) {
                    this.SonucBirimField = value;
                    this.RaisePropertyChanged("SonucBirim");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string SonucReferans {
            get {
                return this.SonucReferansField;
            }
            set {
                if ((object.ReferenceEquals(this.SonucReferansField, value) != true)) {
                    this.SonucReferansField = value;
                    this.RaisePropertyChanged("SonucReferans");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string SonucDurum {
            get {
                return this.SonucDurumField;
            }
            set {
                if ((object.ReferenceEquals(this.SonucDurumField, value) != true)) {
                    this.SonucDurumField = value;
                    this.RaisePropertyChanged("SonucDurum");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
        public string SonucOnayTarihi {
            get {
                return this.SonucOnayTarihiField;
            }
            set {
                if ((object.ReferenceEquals(this.SonucOnayTarihiField, value) != true)) {
                    this.SonucOnayTarihiField = value;
                    this.RaisePropertyChanged("SonucOnayTarihi");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=10)]
        public string SonucYorum {
            get {
                return this.SonucYorumField;
            }
            set {
                if ((object.ReferenceEquals(this.SonucYorumField, value) != true)) {
                    this.SonucYorumField = value;
                    this.RaisePropertyChanged("SonucYorum");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=11)]
        public string SonucAciklama {
            get {
                return this.SonucAciklamaField;
            }
            set {
                if ((object.ReferenceEquals(this.SonucAciklamaField, value) != true)) {
                    this.SonucAciklamaField = value;
                    this.RaisePropertyChanged("SonucAciklama");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="HastaSonucToplu", Namespace="http://www.esy.com.tr/")]
    [System.SerializableAttribute()]
    public partial class HastaSonucToplu : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WindowsFormsApplication1.ws_Adana_Lab_Entegre.HastaSonucBilgisi[] TestSonuclariGenelField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string HataField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public WindowsFormsApplication1.ws_Adana_Lab_Entegre.HastaSonucBilgisi[] TestSonuclariGenel {
            get {
                return this.TestSonuclariGenelField;
            }
            set {
                if ((object.ReferenceEquals(this.TestSonuclariGenelField, value) != true)) {
                    this.TestSonuclariGenelField = value;
                    this.RaisePropertyChanged("TestSonuclariGenel");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Hata {
            get {
                return this.HataField;
            }
            set {
                if ((object.ReferenceEquals(this.HataField, value) != true)) {
                    this.HataField = value;
                    this.RaisePropertyChanged("Hata");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Duyurular", Namespace="http://www.esy.com.tr/")]
    [System.SerializableAttribute()]
    public partial class Duyurular : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DuyuruIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BaslikField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IcerikField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string HataField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string DuyuruID {
            get {
                return this.DuyuruIDField;
            }
            set {
                if ((object.ReferenceEquals(this.DuyuruIDField, value) != true)) {
                    this.DuyuruIDField = value;
                    this.RaisePropertyChanged("DuyuruID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Baslik {
            get {
                return this.BaslikField;
            }
            set {
                if ((object.ReferenceEquals(this.BaslikField, value) != true)) {
                    this.BaslikField = value;
                    this.RaisePropertyChanged("Baslik");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Icerik {
            get {
                return this.IcerikField;
            }
            set {
                if ((object.ReferenceEquals(this.IcerikField, value) != true)) {
                    this.IcerikField = value;
                    this.RaisePropertyChanged("Icerik");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Hata {
            get {
                return this.HataField;
            }
            set {
                if ((object.ReferenceEquals(this.HataField, value) != true)) {
                    this.HataField = value;
                    this.RaisePropertyChanged("Hata");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.esy.com.tr/", ConfigurationName="ws_Adana_Lab_Entegre.EntegreLBYSLabServiceSoap")]
    public interface EntegreLBYSLabServiceSoap {
        
        // CODEGEN: Generating message contract since element name Kadi from namespace http://www.esy.com.tr/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://www.esy.com.tr/AktifTestler", ReplyAction="*")]
        WindowsFormsApplication1.ws_Adana_Lab_Entegre.AktifTestlerResponse AktifTestler(WindowsFormsApplication1.ws_Adana_Lab_Entegre.AktifTestlerRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.esy.com.tr/AktifTestler", ReplyAction="*")]
        System.Threading.Tasks.Task<WindowsFormsApplication1.ws_Adana_Lab_Entegre.AktifTestlerResponse> AktifTestlerAsync(WindowsFormsApplication1.ws_Adana_Lab_Entegre.AktifTestlerRequest request);
        
        // CODEGEN: Generating message contract since element name Kadi from namespace http://www.esy.com.tr/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://www.esy.com.tr/TestEkle", ReplyAction="*")]
        WindowsFormsApplication1.ws_Adana_Lab_Entegre.TestEkleResponse TestEkle(WindowsFormsApplication1.ws_Adana_Lab_Entegre.TestEkleRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.esy.com.tr/TestEkle", ReplyAction="*")]
        System.Threading.Tasks.Task<WindowsFormsApplication1.ws_Adana_Lab_Entegre.TestEkleResponse> TestEkleAsync(WindowsFormsApplication1.ws_Adana_Lab_Entegre.TestEkleRequest request);
        
        // CODEGEN: Generating message contract since element name BARKOD from namespace http://www.esy.com.tr/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://www.esy.com.tr/TestGuncelle", ReplyAction="*")]
        WindowsFormsApplication1.ws_Adana_Lab_Entegre.TestGuncelleResponse TestGuncelle(WindowsFormsApplication1.ws_Adana_Lab_Entegre.TestGuncelleRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.esy.com.tr/TestGuncelle", ReplyAction="*")]
        System.Threading.Tasks.Task<WindowsFormsApplication1.ws_Adana_Lab_Entegre.TestGuncelleResponse> TestGuncelleAsync(WindowsFormsApplication1.ws_Adana_Lab_Entegre.TestGuncelleRequest request);
        
        // CODEGEN: Generating message contract since element name BARKOD from namespace http://www.esy.com.tr/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://www.esy.com.tr/BarkodSonucBilgisi", ReplyAction="*")]
        WindowsFormsApplication1.ws_Adana_Lab_Entegre.BarkodSonucBilgisiResponse BarkodSonucBilgisi(WindowsFormsApplication1.ws_Adana_Lab_Entegre.BarkodSonucBilgisiRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.esy.com.tr/BarkodSonucBilgisi", ReplyAction="*")]
        System.Threading.Tasks.Task<WindowsFormsApplication1.ws_Adana_Lab_Entegre.BarkodSonucBilgisiResponse> BarkodSonucBilgisiAsync(WindowsFormsApplication1.ws_Adana_Lab_Entegre.BarkodSonucBilgisiRequest request);
        
        // CODEGEN: Generating message contract since element name Kadi from namespace http://www.esy.com.tr/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://www.esy.com.tr/TCSonucBilgisi", ReplyAction="*")]
        WindowsFormsApplication1.ws_Adana_Lab_Entegre.TCSonucBilgisiResponse TCSonucBilgisi(WindowsFormsApplication1.ws_Adana_Lab_Entegre.TCSonucBilgisiRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.esy.com.tr/TCSonucBilgisi", ReplyAction="*")]
        System.Threading.Tasks.Task<WindowsFormsApplication1.ws_Adana_Lab_Entegre.TCSonucBilgisiResponse> TCSonucBilgisiAsync(WindowsFormsApplication1.ws_Adana_Lab_Entegre.TCSonucBilgisiRequest request);
        
        // CODEGEN: Generating message contract since element name Kadi from namespace http://www.esy.com.tr/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://www.esy.com.tr/BarkodSil", ReplyAction="*")]
        WindowsFormsApplication1.ws_Adana_Lab_Entegre.BarkodSilResponse BarkodSil(WindowsFormsApplication1.ws_Adana_Lab_Entegre.BarkodSilRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.esy.com.tr/BarkodSil", ReplyAction="*")]
        System.Threading.Tasks.Task<WindowsFormsApplication1.ws_Adana_Lab_Entegre.BarkodSilResponse> BarkodSilAsync(WindowsFormsApplication1.ws_Adana_Lab_Entegre.BarkodSilRequest request);
        
        // CODEGEN: Generating message contract since element name Kadi from namespace http://www.esy.com.tr/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://www.esy.com.tr/DuyurulariGetir", ReplyAction="*")]
        WindowsFormsApplication1.ws_Adana_Lab_Entegre.DuyurulariGetirResponse DuyurulariGetir(WindowsFormsApplication1.ws_Adana_Lab_Entegre.DuyurulariGetirRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.esy.com.tr/DuyurulariGetir", ReplyAction="*")]
        System.Threading.Tasks.Task<WindowsFormsApplication1.ws_Adana_Lab_Entegre.DuyurulariGetirResponse> DuyurulariGetirAsync(WindowsFormsApplication1.ws_Adana_Lab_Entegre.DuyurulariGetirRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AktifTestlerRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AktifTestler", Namespace="http://www.esy.com.tr/", Order=0)]
        public WindowsFormsApplication1.ws_Adana_Lab_Entegre.AktifTestlerRequestBody Body;
        
        public AktifTestlerRequest() {
        }
        
        public AktifTestlerRequest(WindowsFormsApplication1.ws_Adana_Lab_Entegre.AktifTestlerRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.esy.com.tr/")]
    public partial class AktifTestlerRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Kadi;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Ksifre;
        
        public AktifTestlerRequestBody() {
        }
        
        public AktifTestlerRequestBody(string Kadi, string Ksifre) {
            this.Kadi = Kadi;
            this.Ksifre = Ksifre;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AktifTestlerResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AktifTestlerResponse", Namespace="http://www.esy.com.tr/", Order=0)]
        public WindowsFormsApplication1.ws_Adana_Lab_Entegre.AktifTestlerResponseBody Body;
        
        public AktifTestlerResponse() {
        }
        
        public AktifTestlerResponse(WindowsFormsApplication1.ws_Adana_Lab_Entegre.AktifTestlerResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.esy.com.tr/")]
    public partial class AktifTestlerResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public WindowsFormsApplication1.ws_Adana_Lab_Entegre.AktifTest[] AktifTestlerResult;
        
        public AktifTestlerResponseBody() {
        }
        
        public AktifTestlerResponseBody(WindowsFormsApplication1.ws_Adana_Lab_Entegre.AktifTest[] AktifTestlerResult) {
            this.AktifTestlerResult = AktifTestlerResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TestEkleRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="TestEkle", Namespace="http://www.esy.com.tr/", Order=0)]
        public WindowsFormsApplication1.ws_Adana_Lab_Entegre.TestEkleRequestBody Body;
        
        public TestEkleRequest() {
        }
        
        public TestEkleRequest(WindowsFormsApplication1.ws_Adana_Lab_Entegre.TestEkleRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.esy.com.tr/")]
    public partial class TestEkleRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Kadi;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Ksifre;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string BARKOD;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string TCKIMLIK;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string ADI;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string SOYADI;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string CINSIYET;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=7)]
        public System.DateTime DTARIH;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string ONTANI;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
        public WindowsFormsApplication1.ws_Adana_Lab_Entegre.ArrayOfInt Test;
        
        public TestEkleRequestBody() {
        }
        
        public TestEkleRequestBody(string Kadi, string Ksifre, string BARKOD, string TCKIMLIK, string ADI, string SOYADI, string CINSIYET, System.DateTime DTARIH, string ONTANI, WindowsFormsApplication1.ws_Adana_Lab_Entegre.ArrayOfInt Test) {
            this.Kadi = Kadi;
            this.Ksifre = Ksifre;
            this.BARKOD = BARKOD;
            this.TCKIMLIK = TCKIMLIK;
            this.ADI = ADI;
            this.SOYADI = SOYADI;
            this.CINSIYET = CINSIYET;
            this.DTARIH = DTARIH;
            this.ONTANI = ONTANI;
            this.Test = Test;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TestEkleResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="TestEkleResponse", Namespace="http://www.esy.com.tr/", Order=0)]
        public WindowsFormsApplication1.ws_Adana_Lab_Entegre.TestEkleResponseBody Body;
        
        public TestEkleResponse() {
        }
        
        public TestEkleResponse(WindowsFormsApplication1.ws_Adana_Lab_Entegre.TestEkleResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.esy.com.tr/")]
    public partial class TestEkleResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public WindowsFormsApplication1.ws_Adana_Lab_Entegre.TestEkleSonuc[] TestEkleResult;
        
        public TestEkleResponseBody() {
        }
        
        public TestEkleResponseBody(WindowsFormsApplication1.ws_Adana_Lab_Entegre.TestEkleSonuc[] TestEkleResult) {
            this.TestEkleResult = TestEkleResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TestGuncelleRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="TestGuncelle", Namespace="http://www.esy.com.tr/", Order=0)]
        public WindowsFormsApplication1.ws_Adana_Lab_Entegre.TestGuncelleRequestBody Body;
        
        public TestGuncelleRequest() {
        }
        
        public TestGuncelleRequest(WindowsFormsApplication1.ws_Adana_Lab_Entegre.TestGuncelleRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.esy.com.tr/")]
    public partial class TestGuncelleRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string BARKOD;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Kadi;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Ksifre;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public WindowsFormsApplication1.ws_Adana_Lab_Entegre.ArrayOfInt Test;
        
        public TestGuncelleRequestBody() {
        }
        
        public TestGuncelleRequestBody(string BARKOD, string Kadi, string Ksifre, WindowsFormsApplication1.ws_Adana_Lab_Entegre.ArrayOfInt Test) {
            this.BARKOD = BARKOD;
            this.Kadi = Kadi;
            this.Ksifre = Ksifre;
            this.Test = Test;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TestGuncelleResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="TestGuncelleResponse", Namespace="http://www.esy.com.tr/", Order=0)]
        public WindowsFormsApplication1.ws_Adana_Lab_Entegre.TestGuncelleResponseBody Body;
        
        public TestGuncelleResponse() {
        }
        
        public TestGuncelleResponse(WindowsFormsApplication1.ws_Adana_Lab_Entegre.TestGuncelleResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.esy.com.tr/")]
    public partial class TestGuncelleResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string TestGuncelleResult;
        
        public TestGuncelleResponseBody() {
        }
        
        public TestGuncelleResponseBody(string TestGuncelleResult) {
            this.TestGuncelleResult = TestGuncelleResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class BarkodSonucBilgisiRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="BarkodSonucBilgisi", Namespace="http://www.esy.com.tr/", Order=0)]
        public WindowsFormsApplication1.ws_Adana_Lab_Entegre.BarkodSonucBilgisiRequestBody Body;
        
        public BarkodSonucBilgisiRequest() {
        }
        
        public BarkodSonucBilgisiRequest(WindowsFormsApplication1.ws_Adana_Lab_Entegre.BarkodSonucBilgisiRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.esy.com.tr/")]
    public partial class BarkodSonucBilgisiRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string BARKOD;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Kadi;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Ksifre;
        
        public BarkodSonucBilgisiRequestBody() {
        }
        
        public BarkodSonucBilgisiRequestBody(string BARKOD, string Kadi, string Ksifre) {
            this.BARKOD = BARKOD;
            this.Kadi = Kadi;
            this.Ksifre = Ksifre;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class BarkodSonucBilgisiResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="BarkodSonucBilgisiResponse", Namespace="http://www.esy.com.tr/", Order=0)]
        public WindowsFormsApplication1.ws_Adana_Lab_Entegre.BarkodSonucBilgisiResponseBody Body;
        
        public BarkodSonucBilgisiResponse() {
        }
        
        public BarkodSonucBilgisiResponse(WindowsFormsApplication1.ws_Adana_Lab_Entegre.BarkodSonucBilgisiResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.esy.com.tr/")]
    public partial class BarkodSonucBilgisiResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public WindowsFormsApplication1.ws_Adana_Lab_Entegre.HastaSonucBilgisi[] BarkodSonucBilgisiResult;
        
        public BarkodSonucBilgisiResponseBody() {
        }
        
        public BarkodSonucBilgisiResponseBody(WindowsFormsApplication1.ws_Adana_Lab_Entegre.HastaSonucBilgisi[] BarkodSonucBilgisiResult) {
            this.BarkodSonucBilgisiResult = BarkodSonucBilgisiResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TCSonucBilgisiRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="TCSonucBilgisi", Namespace="http://www.esy.com.tr/", Order=0)]
        public WindowsFormsApplication1.ws_Adana_Lab_Entegre.TCSonucBilgisiRequestBody Body;
        
        public TCSonucBilgisiRequest() {
        }
        
        public TCSonucBilgisiRequest(WindowsFormsApplication1.ws_Adana_Lab_Entegre.TCSonucBilgisiRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.esy.com.tr/")]
    public partial class TCSonucBilgisiRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Kadi;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Ksifre;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string TCKIMLIK;
        
        public TCSonucBilgisiRequestBody() {
        }
        
        public TCSonucBilgisiRequestBody(string Kadi, string Ksifre, string TCKIMLIK) {
            this.Kadi = Kadi;
            this.Ksifre = Ksifre;
            this.TCKIMLIK = TCKIMLIK;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TCSonucBilgisiResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="TCSonucBilgisiResponse", Namespace="http://www.esy.com.tr/", Order=0)]
        public WindowsFormsApplication1.ws_Adana_Lab_Entegre.TCSonucBilgisiResponseBody Body;
        
        public TCSonucBilgisiResponse() {
        }
        
        public TCSonucBilgisiResponse(WindowsFormsApplication1.ws_Adana_Lab_Entegre.TCSonucBilgisiResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.esy.com.tr/")]
    public partial class TCSonucBilgisiResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public WindowsFormsApplication1.ws_Adana_Lab_Entegre.HastaSonucToplu[] TCSonucBilgisiResult;
        
        public TCSonucBilgisiResponseBody() {
        }
        
        public TCSonucBilgisiResponseBody(WindowsFormsApplication1.ws_Adana_Lab_Entegre.HastaSonucToplu[] TCSonucBilgisiResult) {
            this.TCSonucBilgisiResult = TCSonucBilgisiResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class BarkodSilRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="BarkodSil", Namespace="http://www.esy.com.tr/", Order=0)]
        public WindowsFormsApplication1.ws_Adana_Lab_Entegre.BarkodSilRequestBody Body;
        
        public BarkodSilRequest() {
        }
        
        public BarkodSilRequest(WindowsFormsApplication1.ws_Adana_Lab_Entegre.BarkodSilRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.esy.com.tr/")]
    public partial class BarkodSilRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Kadi;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Ksifre;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string barkod;
        
        public BarkodSilRequestBody() {
        }
        
        public BarkodSilRequestBody(string Kadi, string Ksifre, string barkod) {
            this.Kadi = Kadi;
            this.Ksifre = Ksifre;
            this.barkod = barkod;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class BarkodSilResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="BarkodSilResponse", Namespace="http://www.esy.com.tr/", Order=0)]
        public WindowsFormsApplication1.ws_Adana_Lab_Entegre.BarkodSilResponseBody Body;
        
        public BarkodSilResponse() {
        }
        
        public BarkodSilResponse(WindowsFormsApplication1.ws_Adana_Lab_Entegre.BarkodSilResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.esy.com.tr/")]
    public partial class BarkodSilResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string BarkodSilResult;
        
        public BarkodSilResponseBody() {
        }
        
        public BarkodSilResponseBody(string BarkodSilResult) {
            this.BarkodSilResult = BarkodSilResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DuyurulariGetirRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DuyurulariGetir", Namespace="http://www.esy.com.tr/", Order=0)]
        public WindowsFormsApplication1.ws_Adana_Lab_Entegre.DuyurulariGetirRequestBody Body;
        
        public DuyurulariGetirRequest() {
        }
        
        public DuyurulariGetirRequest(WindowsFormsApplication1.ws_Adana_Lab_Entegre.DuyurulariGetirRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.esy.com.tr/")]
    public partial class DuyurulariGetirRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Kadi;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Ksifre;
        
        public DuyurulariGetirRequestBody() {
        }
        
        public DuyurulariGetirRequestBody(string Kadi, string Ksifre) {
            this.Kadi = Kadi;
            this.Ksifre = Ksifre;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DuyurulariGetirResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DuyurulariGetirResponse", Namespace="http://www.esy.com.tr/", Order=0)]
        public WindowsFormsApplication1.ws_Adana_Lab_Entegre.DuyurulariGetirResponseBody Body;
        
        public DuyurulariGetirResponse() {
        }
        
        public DuyurulariGetirResponse(WindowsFormsApplication1.ws_Adana_Lab_Entegre.DuyurulariGetirResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.esy.com.tr/")]
    public partial class DuyurulariGetirResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public WindowsFormsApplication1.ws_Adana_Lab_Entegre.Duyurular[] DuyurulariGetirResult;
        
        public DuyurulariGetirResponseBody() {
        }
        
        public DuyurulariGetirResponseBody(WindowsFormsApplication1.ws_Adana_Lab_Entegre.Duyurular[] DuyurulariGetirResult) {
            this.DuyurulariGetirResult = DuyurulariGetirResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface EntegreLBYSLabServiceSoapChannel : WindowsFormsApplication1.ws_Adana_Lab_Entegre.EntegreLBYSLabServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class EntegreLBYSLabServiceSoapClient : System.ServiceModel.ClientBase<WindowsFormsApplication1.ws_Adana_Lab_Entegre.EntegreLBYSLabServiceSoap>, WindowsFormsApplication1.ws_Adana_Lab_Entegre.EntegreLBYSLabServiceSoap {
        
        public EntegreLBYSLabServiceSoapClient() {
        }
        
        public EntegreLBYSLabServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public EntegreLBYSLabServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EntegreLBYSLabServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EntegreLBYSLabServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WindowsFormsApplication1.ws_Adana_Lab_Entegre.AktifTestlerResponse WindowsFormsApplication1.ws_Adana_Lab_Entegre.EntegreLBYSLabServiceSoap.AktifTestler(WindowsFormsApplication1.ws_Adana_Lab_Entegre.AktifTestlerRequest request) {
            return base.Channel.AktifTestler(request);
        }
        
        public WindowsFormsApplication1.ws_Adana_Lab_Entegre.AktifTest[] AktifTestler(string Kadi, string Ksifre) {
            WindowsFormsApplication1.ws_Adana_Lab_Entegre.AktifTestlerRequest inValue = new WindowsFormsApplication1.ws_Adana_Lab_Entegre.AktifTestlerRequest();
            inValue.Body = new WindowsFormsApplication1.ws_Adana_Lab_Entegre.AktifTestlerRequestBody();
            inValue.Body.Kadi = Kadi;
            inValue.Body.Ksifre = Ksifre;
            WindowsFormsApplication1.ws_Adana_Lab_Entegre.AktifTestlerResponse retVal = ((WindowsFormsApplication1.ws_Adana_Lab_Entegre.EntegreLBYSLabServiceSoap)(this)).AktifTestler(inValue);
            return retVal.Body.AktifTestlerResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WindowsFormsApplication1.ws_Adana_Lab_Entegre.AktifTestlerResponse> WindowsFormsApplication1.ws_Adana_Lab_Entegre.EntegreLBYSLabServiceSoap.AktifTestlerAsync(WindowsFormsApplication1.ws_Adana_Lab_Entegre.AktifTestlerRequest request) {
            return base.Channel.AktifTestlerAsync(request);
        }
        
        public System.Threading.Tasks.Task<WindowsFormsApplication1.ws_Adana_Lab_Entegre.AktifTestlerResponse> AktifTestlerAsync(string Kadi, string Ksifre) {
            WindowsFormsApplication1.ws_Adana_Lab_Entegre.AktifTestlerRequest inValue = new WindowsFormsApplication1.ws_Adana_Lab_Entegre.AktifTestlerRequest();
            inValue.Body = new WindowsFormsApplication1.ws_Adana_Lab_Entegre.AktifTestlerRequestBody();
            inValue.Body.Kadi = Kadi;
            inValue.Body.Ksifre = Ksifre;
            return ((WindowsFormsApplication1.ws_Adana_Lab_Entegre.EntegreLBYSLabServiceSoap)(this)).AktifTestlerAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WindowsFormsApplication1.ws_Adana_Lab_Entegre.TestEkleResponse WindowsFormsApplication1.ws_Adana_Lab_Entegre.EntegreLBYSLabServiceSoap.TestEkle(WindowsFormsApplication1.ws_Adana_Lab_Entegre.TestEkleRequest request) {
            return base.Channel.TestEkle(request);
        }
        
        public WindowsFormsApplication1.ws_Adana_Lab_Entegre.TestEkleSonuc[] TestEkle(string Kadi, string Ksifre, string BARKOD, string TCKIMLIK, string ADI, string SOYADI, string CINSIYET, System.DateTime DTARIH, string ONTANI, WindowsFormsApplication1.ws_Adana_Lab_Entegre.ArrayOfInt Test) {
            WindowsFormsApplication1.ws_Adana_Lab_Entegre.TestEkleRequest inValue = new WindowsFormsApplication1.ws_Adana_Lab_Entegre.TestEkleRequest();
            inValue.Body = new WindowsFormsApplication1.ws_Adana_Lab_Entegre.TestEkleRequestBody();
            inValue.Body.Kadi = Kadi;
            inValue.Body.Ksifre = Ksifre;
            inValue.Body.BARKOD = BARKOD;
            inValue.Body.TCKIMLIK = TCKIMLIK;
            inValue.Body.ADI = ADI;
            inValue.Body.SOYADI = SOYADI;
            inValue.Body.CINSIYET = CINSIYET;
            inValue.Body.DTARIH = DTARIH;
            inValue.Body.ONTANI = ONTANI;
            inValue.Body.Test = Test;
            WindowsFormsApplication1.ws_Adana_Lab_Entegre.TestEkleResponse retVal = ((WindowsFormsApplication1.ws_Adana_Lab_Entegre.EntegreLBYSLabServiceSoap)(this)).TestEkle(inValue);
            return retVal.Body.TestEkleResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WindowsFormsApplication1.ws_Adana_Lab_Entegre.TestEkleResponse> WindowsFormsApplication1.ws_Adana_Lab_Entegre.EntegreLBYSLabServiceSoap.TestEkleAsync(WindowsFormsApplication1.ws_Adana_Lab_Entegre.TestEkleRequest request) {
            return base.Channel.TestEkleAsync(request);
        }
        
        public System.Threading.Tasks.Task<WindowsFormsApplication1.ws_Adana_Lab_Entegre.TestEkleResponse> TestEkleAsync(string Kadi, string Ksifre, string BARKOD, string TCKIMLIK, string ADI, string SOYADI, string CINSIYET, System.DateTime DTARIH, string ONTANI, WindowsFormsApplication1.ws_Adana_Lab_Entegre.ArrayOfInt Test) {
            WindowsFormsApplication1.ws_Adana_Lab_Entegre.TestEkleRequest inValue = new WindowsFormsApplication1.ws_Adana_Lab_Entegre.TestEkleRequest();
            inValue.Body = new WindowsFormsApplication1.ws_Adana_Lab_Entegre.TestEkleRequestBody();
            inValue.Body.Kadi = Kadi;
            inValue.Body.Ksifre = Ksifre;
            inValue.Body.BARKOD = BARKOD;
            inValue.Body.TCKIMLIK = TCKIMLIK;
            inValue.Body.ADI = ADI;
            inValue.Body.SOYADI = SOYADI;
            inValue.Body.CINSIYET = CINSIYET;
            inValue.Body.DTARIH = DTARIH;
            inValue.Body.ONTANI = ONTANI;
            inValue.Body.Test = Test;
            return ((WindowsFormsApplication1.ws_Adana_Lab_Entegre.EntegreLBYSLabServiceSoap)(this)).TestEkleAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WindowsFormsApplication1.ws_Adana_Lab_Entegre.TestGuncelleResponse WindowsFormsApplication1.ws_Adana_Lab_Entegre.EntegreLBYSLabServiceSoap.TestGuncelle(WindowsFormsApplication1.ws_Adana_Lab_Entegre.TestGuncelleRequest request) {
            return base.Channel.TestGuncelle(request);
        }
        
        public string TestGuncelle(string BARKOD, string Kadi, string Ksifre, WindowsFormsApplication1.ws_Adana_Lab_Entegre.ArrayOfInt Test) {
            WindowsFormsApplication1.ws_Adana_Lab_Entegre.TestGuncelleRequest inValue = new WindowsFormsApplication1.ws_Adana_Lab_Entegre.TestGuncelleRequest();
            inValue.Body = new WindowsFormsApplication1.ws_Adana_Lab_Entegre.TestGuncelleRequestBody();
            inValue.Body.BARKOD = BARKOD;
            inValue.Body.Kadi = Kadi;
            inValue.Body.Ksifre = Ksifre;
            inValue.Body.Test = Test;
            WindowsFormsApplication1.ws_Adana_Lab_Entegre.TestGuncelleResponse retVal = ((WindowsFormsApplication1.ws_Adana_Lab_Entegre.EntegreLBYSLabServiceSoap)(this)).TestGuncelle(inValue);
            return retVal.Body.TestGuncelleResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WindowsFormsApplication1.ws_Adana_Lab_Entegre.TestGuncelleResponse> WindowsFormsApplication1.ws_Adana_Lab_Entegre.EntegreLBYSLabServiceSoap.TestGuncelleAsync(WindowsFormsApplication1.ws_Adana_Lab_Entegre.TestGuncelleRequest request) {
            return base.Channel.TestGuncelleAsync(request);
        }
        
        public System.Threading.Tasks.Task<WindowsFormsApplication1.ws_Adana_Lab_Entegre.TestGuncelleResponse> TestGuncelleAsync(string BARKOD, string Kadi, string Ksifre, WindowsFormsApplication1.ws_Adana_Lab_Entegre.ArrayOfInt Test) {
            WindowsFormsApplication1.ws_Adana_Lab_Entegre.TestGuncelleRequest inValue = new WindowsFormsApplication1.ws_Adana_Lab_Entegre.TestGuncelleRequest();
            inValue.Body = new WindowsFormsApplication1.ws_Adana_Lab_Entegre.TestGuncelleRequestBody();
            inValue.Body.BARKOD = BARKOD;
            inValue.Body.Kadi = Kadi;
            inValue.Body.Ksifre = Ksifre;
            inValue.Body.Test = Test;
            return ((WindowsFormsApplication1.ws_Adana_Lab_Entegre.EntegreLBYSLabServiceSoap)(this)).TestGuncelleAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WindowsFormsApplication1.ws_Adana_Lab_Entegre.BarkodSonucBilgisiResponse WindowsFormsApplication1.ws_Adana_Lab_Entegre.EntegreLBYSLabServiceSoap.BarkodSonucBilgisi(WindowsFormsApplication1.ws_Adana_Lab_Entegre.BarkodSonucBilgisiRequest request) {
            return base.Channel.BarkodSonucBilgisi(request);
        }
        
        public WindowsFormsApplication1.ws_Adana_Lab_Entegre.HastaSonucBilgisi[] BarkodSonucBilgisi(string BARKOD, string Kadi, string Ksifre) {
            WindowsFormsApplication1.ws_Adana_Lab_Entegre.BarkodSonucBilgisiRequest inValue = new WindowsFormsApplication1.ws_Adana_Lab_Entegre.BarkodSonucBilgisiRequest();
            inValue.Body = new WindowsFormsApplication1.ws_Adana_Lab_Entegre.BarkodSonucBilgisiRequestBody();
            inValue.Body.BARKOD = BARKOD;
            inValue.Body.Kadi = Kadi;
            inValue.Body.Ksifre = Ksifre;
            WindowsFormsApplication1.ws_Adana_Lab_Entegre.BarkodSonucBilgisiResponse retVal = ((WindowsFormsApplication1.ws_Adana_Lab_Entegre.EntegreLBYSLabServiceSoap)(this)).BarkodSonucBilgisi(inValue);
            return retVal.Body.BarkodSonucBilgisiResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WindowsFormsApplication1.ws_Adana_Lab_Entegre.BarkodSonucBilgisiResponse> WindowsFormsApplication1.ws_Adana_Lab_Entegre.EntegreLBYSLabServiceSoap.BarkodSonucBilgisiAsync(WindowsFormsApplication1.ws_Adana_Lab_Entegre.BarkodSonucBilgisiRequest request) {
            return base.Channel.BarkodSonucBilgisiAsync(request);
        }
        
        public System.Threading.Tasks.Task<WindowsFormsApplication1.ws_Adana_Lab_Entegre.BarkodSonucBilgisiResponse> BarkodSonucBilgisiAsync(string BARKOD, string Kadi, string Ksifre) {
            WindowsFormsApplication1.ws_Adana_Lab_Entegre.BarkodSonucBilgisiRequest inValue = new WindowsFormsApplication1.ws_Adana_Lab_Entegre.BarkodSonucBilgisiRequest();
            inValue.Body = new WindowsFormsApplication1.ws_Adana_Lab_Entegre.BarkodSonucBilgisiRequestBody();
            inValue.Body.BARKOD = BARKOD;
            inValue.Body.Kadi = Kadi;
            inValue.Body.Ksifre = Ksifre;
            return ((WindowsFormsApplication1.ws_Adana_Lab_Entegre.EntegreLBYSLabServiceSoap)(this)).BarkodSonucBilgisiAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WindowsFormsApplication1.ws_Adana_Lab_Entegre.TCSonucBilgisiResponse WindowsFormsApplication1.ws_Adana_Lab_Entegre.EntegreLBYSLabServiceSoap.TCSonucBilgisi(WindowsFormsApplication1.ws_Adana_Lab_Entegre.TCSonucBilgisiRequest request) {
            return base.Channel.TCSonucBilgisi(request);
        }
        
        public WindowsFormsApplication1.ws_Adana_Lab_Entegre.HastaSonucToplu[] TCSonucBilgisi(string Kadi, string Ksifre, string TCKIMLIK) {
            WindowsFormsApplication1.ws_Adana_Lab_Entegre.TCSonucBilgisiRequest inValue = new WindowsFormsApplication1.ws_Adana_Lab_Entegre.TCSonucBilgisiRequest();
            inValue.Body = new WindowsFormsApplication1.ws_Adana_Lab_Entegre.TCSonucBilgisiRequestBody();
            inValue.Body.Kadi = Kadi;
            inValue.Body.Ksifre = Ksifre;
            inValue.Body.TCKIMLIK = TCKIMLIK;
            WindowsFormsApplication1.ws_Adana_Lab_Entegre.TCSonucBilgisiResponse retVal = ((WindowsFormsApplication1.ws_Adana_Lab_Entegre.EntegreLBYSLabServiceSoap)(this)).TCSonucBilgisi(inValue);
            return retVal.Body.TCSonucBilgisiResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WindowsFormsApplication1.ws_Adana_Lab_Entegre.TCSonucBilgisiResponse> WindowsFormsApplication1.ws_Adana_Lab_Entegre.EntegreLBYSLabServiceSoap.TCSonucBilgisiAsync(WindowsFormsApplication1.ws_Adana_Lab_Entegre.TCSonucBilgisiRequest request) {
            return base.Channel.TCSonucBilgisiAsync(request);
        }
        
        public System.Threading.Tasks.Task<WindowsFormsApplication1.ws_Adana_Lab_Entegre.TCSonucBilgisiResponse> TCSonucBilgisiAsync(string Kadi, string Ksifre, string TCKIMLIK) {
            WindowsFormsApplication1.ws_Adana_Lab_Entegre.TCSonucBilgisiRequest inValue = new WindowsFormsApplication1.ws_Adana_Lab_Entegre.TCSonucBilgisiRequest();
            inValue.Body = new WindowsFormsApplication1.ws_Adana_Lab_Entegre.TCSonucBilgisiRequestBody();
            inValue.Body.Kadi = Kadi;
            inValue.Body.Ksifre = Ksifre;
            inValue.Body.TCKIMLIK = TCKIMLIK;
            return ((WindowsFormsApplication1.ws_Adana_Lab_Entegre.EntegreLBYSLabServiceSoap)(this)).TCSonucBilgisiAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WindowsFormsApplication1.ws_Adana_Lab_Entegre.BarkodSilResponse WindowsFormsApplication1.ws_Adana_Lab_Entegre.EntegreLBYSLabServiceSoap.BarkodSil(WindowsFormsApplication1.ws_Adana_Lab_Entegre.BarkodSilRequest request) {
            return base.Channel.BarkodSil(request);
        }
        
        public string BarkodSil(string Kadi, string Ksifre, string barkod) {
            WindowsFormsApplication1.ws_Adana_Lab_Entegre.BarkodSilRequest inValue = new WindowsFormsApplication1.ws_Adana_Lab_Entegre.BarkodSilRequest();
            inValue.Body = new WindowsFormsApplication1.ws_Adana_Lab_Entegre.BarkodSilRequestBody();
            inValue.Body.Kadi = Kadi;
            inValue.Body.Ksifre = Ksifre;
            inValue.Body.barkod = barkod;
            WindowsFormsApplication1.ws_Adana_Lab_Entegre.BarkodSilResponse retVal = ((WindowsFormsApplication1.ws_Adana_Lab_Entegre.EntegreLBYSLabServiceSoap)(this)).BarkodSil(inValue);
            return retVal.Body.BarkodSilResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WindowsFormsApplication1.ws_Adana_Lab_Entegre.BarkodSilResponse> WindowsFormsApplication1.ws_Adana_Lab_Entegre.EntegreLBYSLabServiceSoap.BarkodSilAsync(WindowsFormsApplication1.ws_Adana_Lab_Entegre.BarkodSilRequest request) {
            return base.Channel.BarkodSilAsync(request);
        }
        
        public System.Threading.Tasks.Task<WindowsFormsApplication1.ws_Adana_Lab_Entegre.BarkodSilResponse> BarkodSilAsync(string Kadi, string Ksifre, string barkod) {
            WindowsFormsApplication1.ws_Adana_Lab_Entegre.BarkodSilRequest inValue = new WindowsFormsApplication1.ws_Adana_Lab_Entegre.BarkodSilRequest();
            inValue.Body = new WindowsFormsApplication1.ws_Adana_Lab_Entegre.BarkodSilRequestBody();
            inValue.Body.Kadi = Kadi;
            inValue.Body.Ksifre = Ksifre;
            inValue.Body.barkod = barkod;
            return ((WindowsFormsApplication1.ws_Adana_Lab_Entegre.EntegreLBYSLabServiceSoap)(this)).BarkodSilAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WindowsFormsApplication1.ws_Adana_Lab_Entegre.DuyurulariGetirResponse WindowsFormsApplication1.ws_Adana_Lab_Entegre.EntegreLBYSLabServiceSoap.DuyurulariGetir(WindowsFormsApplication1.ws_Adana_Lab_Entegre.DuyurulariGetirRequest request) {
            return base.Channel.DuyurulariGetir(request);
        }
        
        public WindowsFormsApplication1.ws_Adana_Lab_Entegre.Duyurular[] DuyurulariGetir(string Kadi, string Ksifre) {
            WindowsFormsApplication1.ws_Adana_Lab_Entegre.DuyurulariGetirRequest inValue = new WindowsFormsApplication1.ws_Adana_Lab_Entegre.DuyurulariGetirRequest();
            inValue.Body = new WindowsFormsApplication1.ws_Adana_Lab_Entegre.DuyurulariGetirRequestBody();
            inValue.Body.Kadi = Kadi;
            inValue.Body.Ksifre = Ksifre;
            WindowsFormsApplication1.ws_Adana_Lab_Entegre.DuyurulariGetirResponse retVal = ((WindowsFormsApplication1.ws_Adana_Lab_Entegre.EntegreLBYSLabServiceSoap)(this)).DuyurulariGetir(inValue);
            return retVal.Body.DuyurulariGetirResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WindowsFormsApplication1.ws_Adana_Lab_Entegre.DuyurulariGetirResponse> WindowsFormsApplication1.ws_Adana_Lab_Entegre.EntegreLBYSLabServiceSoap.DuyurulariGetirAsync(WindowsFormsApplication1.ws_Adana_Lab_Entegre.DuyurulariGetirRequest request) {
            return base.Channel.DuyurulariGetirAsync(request);
        }
        
        public System.Threading.Tasks.Task<WindowsFormsApplication1.ws_Adana_Lab_Entegre.DuyurulariGetirResponse> DuyurulariGetirAsync(string Kadi, string Ksifre) {
            WindowsFormsApplication1.ws_Adana_Lab_Entegre.DuyurulariGetirRequest inValue = new WindowsFormsApplication1.ws_Adana_Lab_Entegre.DuyurulariGetirRequest();
            inValue.Body = new WindowsFormsApplication1.ws_Adana_Lab_Entegre.DuyurulariGetirRequestBody();
            inValue.Body.Kadi = Kadi;
            inValue.Body.Ksifre = Ksifre;
            return ((WindowsFormsApplication1.ws_Adana_Lab_Entegre.EntegreLBYSLabServiceSoap)(this)).DuyurulariGetirAsync(inValue);
        }
    }
}
