//------------------------------------------------------------------------------
// <auto-generated>
//     Bu kod araç tarafından oluşturuldu.
//     Çalışma Zamanı Sürümü:4.0.30319.42000
//
//     Bu dosyada yapılacak değişiklikler yanlış davranışa neden olabilir ve
//     kod yeniden oluşturulursa kaybolur.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApplication1.HastaWebService {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="HastaWebService.Service1Soap")]
    public interface Service1Soap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TümHasta", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet TümHasta();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TümHasta", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> TümHastaAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Ögrenci_Ekle", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void Ögrenci_Ekle(int Tc, string Ad, string Soyad, string Tel, string Cinsiyet, System.DateTime dt);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Ögrenci_Ekle", ReplyAction="*")]
        System.Threading.Tasks.Task Ögrenci_EkleAsync(int Tc, string Ad, string Soyad, string Tel, string Cinsiyet, System.DateTime dt);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface Service1SoapChannel : WindowsFormsApplication1.HastaWebService.Service1Soap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1SoapClient : System.ServiceModel.ClientBase<WindowsFormsApplication1.HastaWebService.Service1Soap>, WindowsFormsApplication1.HastaWebService.Service1Soap {
        
        public Service1SoapClient() {
        }
        
        public Service1SoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1SoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1SoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Data.DataSet TümHasta() {
            return base.Channel.TümHasta();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> TümHastaAsync() {
            return base.Channel.TümHastaAsync();
        }
        
        public void Ögrenci_Ekle(int Tc, string Ad, string Soyad, string Tel, string Cinsiyet, System.DateTime dt) {
            base.Channel.Ögrenci_Ekle(Tc, Ad, Soyad, Tel, Cinsiyet, dt);
        }
        
        public System.Threading.Tasks.Task Ögrenci_EkleAsync(int Tc, string Ad, string Soyad, string Tel, string Cinsiyet, System.DateTime dt) {
            return base.Channel.Ögrenci_EkleAsync(Tc, Ad, Soyad, Tel, Cinsiyet, dt);
        }
    }
}
